project:
  type: website

website:
  title: "DATA"

  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: courseP.qmd
        text: Cours Python
      - href: exerciceP.qmd
        text: Exercice Python
      - href: CourseR.qmd
        text: Cours R
      - href: exerciceR.qmd
        text: Exercice R
      - about.qmd
      
format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
