project:
  type: website

website:
  title: "Cours sur l'Analyse de Données"
  description: "Apprenez l'analyse de données avec R et Python"
  navbar:
    left:
      - text: "Accueil"
        href: index.html
      - text: "Cours R"
        href: courseR.html
      - text: "Cours Python"
        href: courseP.html
