project:
  type: website

website:
  title: "Cours sur l'Analyse de Données"
  description: "Apprenez l'analyse de données avec R et Python"
  navbar:
    background: primary
    search: true
    left:
      - text: "Accueil"
        href: index.qmd
      - text: "Cours R"
        href: courseR.qmd
      - text: "Cours Python"
        href: courseP.qmd
